server {
  listen 80;
  server_name _;

  location / {
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' http://localhost:8000; frame-src http://localhost:8000 http://localhost:4173; connect-src 'self' http://localhost:8000; style-src 'self' 'unsafe-inline'; img-src 'self' data:; object-src 'none'; base-uri 'none';" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header X-Content-Type-Options "nosniff" always;
    root /usr/share/nginx/html;
    index index.html;
  }
}
